//! The reference of the scripting API, generated from the bindings: the definitions file for
//! Luau's language server (`openreliant.d.luau`), which editors complete names and check types
//! with, the reference page of the hooks (`hooks.md`), and the list `openreliant hooks` prints.
//!
//! `docs/guide` holds the definitions and the reference page as generated, and tests check that
//! they haven't changed. Everything scripts see is in them: the hooks and the fields of their `e`,
//! the names of enum values, the fields of objects and records, the packages and the engine
//! handlers. So a change to OpenReliant's code that would change what scripts see fails the tests,
//! and the scripting API only changes on purpose: then `make definitions` writes the files again.

const std = @import("std");
const Writer = std.Io.Writer;

const openreliant = @import("openreliant");
const engine = openreliant.engine;
const engine_hooks = engine.hooks;
const Hook = engine_hooks.Hook;
const Object = engine_hooks.Object;
const game = engine.game;
const stats = openreliant.stats;
const values = @import("values.zig");
const objects = @import("objects.zig");
const records = @import("records.zig");
const bind = @import("bind.zig");

/// The name each enum scripts see takes in the definitions.
const enum_names = .{
    .{ game.collision.Quadrant, "Quadrant" },
    .{ game.collision.Kind, "DamageKind" },
    .{ game.guns.GunType, "GunType" },
    .{ game.gameobj.Type, "ShipType" },
    .{ game.create.ShipCombat.Class, "ShipClass" },
    .{ game.gameobj.Side(i32), "Side" },
    .{ game.ai.orders.Order, "Order" },
    .{ openreliant.dte.Condition, "Condition" },
    .{ game.main.Ending, "Ending" },
    .{ engine.vm.Variables.Outcome, "Rating" },
    .{ stats.Pilot.Skill, "PilotSkill" },
    .{ stats.Pilot.Tier, "PilotTier" },
};

/// The name of `T`, an enum, in the definitions.
fn enumName(comptime T: type) []const u8 {
    inline for (enum_names) |entry| {
        if (entry[0] == T) return entry[1];
    }
    @compileError("give the enum " ++ @typeName(T) ++ " a name in reference.enum_names");
}

/// The Luau type of a value of `T` (`values.push`).
fn luauType(comptime T: type) []const u8 {
    comptime {
        if (T == Object) return "Object";
        return switch (@typeInfo(T)) {
            .float, .int => "number",
            .bool => "boolean",
            .@"enum" => enumName(T),
            .optional => |optional| luauType(optional.child) ++ "?",
            .vector => "vector",
            .array => |array| if (array.child == u8) "string" else "{ " ++ luauType(array.child) ++ " }",
            .pointer => "string",
            .@"struct" => bind.noun(T),
            else => @compileError("no Luau type for " ++ @typeName(T)),
        };
    }
}

/// The name of the class of `hook`'s `e`: its name in Pascal case, or `OrderRoutine` for the
/// order table's routines, which all see the same fields.
fn eventClass(comptime hook: Hook) []const u8 {
    comptime {
        if (engine_hooks.Fields(hook) == engine_hooks.RoutineFields) return "OrderRoutine";
        var name: []const u8 = "";
        var upper = true;
        for (@tagName(hook)) |c| {
            if (c == '_') {
                upper = true;
                continue;
            }
            name = name ++ .{if (upper) std.ascii.toUpper(c) else c};
            upper = false;
        }
        return name;
    }
}

/// Every enum scripts see, in the order the definitions declare them.
const enums: []const type = list: {
    var found: []const type = &.{};
    for (enum_names) |entry| found = found ++ .{entry[0]};
    break :list found;
};

/// Writes the definitions file.
pub fn writeDefinitions(w: *Writer) Writer.Error!void {
    @setEvalBranchQuota(1_000_000);
    try w.writeAll(
        \\-- The types of OpenReliant's scripting API, for Luau's language server (luau-lsp). Point its
        \\-- luau-lsp.types.definitionFiles setting at this file, and give each package's local its type,
        \\-- such as `local hooks: Hooks = require("openreliant.hooks")`, for completion and type checks.
        \\-- Generated by `openreliant hooks --definitions` from OpenReliant's bindings; don't change it
        \\-- by hand.
        \\
        \\
    );

    try w.writeAll("-- Names of values. A value without a name is a number.\n\n");
    inline for (enums) |T| {
        try w.print("type {s} = ", .{comptime enumName(T)});
        inline for (comptime values.names(T), 0..) |name, at| {
            if (at > 0) try w.writeAll(" | ");
            try w.print("\"{s}\"", .{name});
        }
        if (comptime values.takesNumbers(T)) try w.writeAll(" | number");
        try w.writeAll("\n");
    }

    try w.writeAll("\n-- Objects, which scripts hold by handles.\n\n");
    try w.writeAll("declare class Object\n");
    inline for (comptime std.meta.declarations(objects.fields)) |decl| {
        const field = @field(objects.fields, decl.name);
        try w.print("    -- {s}\n    {s}: {s}\n", .{ field.description, decl.name, comptime luauType(field.Type) });
    }
    inline for (comptime std.meta.declarations(objects.methods)) |decl| {
        try w.print("    -- {s}\n    function {s}(self): boolean\n", .{ @field(objects.methods, decl.name), decl.name });
    }
    try w.writeAll("end\n");

    try w.writeAll("\n-- The records (`openreliant.records`).\n\n");
    inline for (comptime records.Values.kinds) |T| {
        if (@typeInfo(T) != .@"struct") continue;
        try w.print("declare class {s}\n", .{comptime bind.noun(T)});
        inline for (comptime values.shownFields(T)) |field| try w.print("    {s}: {s}\n", .{ field.name, comptime luauType(field.type) });
        try w.writeAll("end\n");
    }
    try w.writeAll("type Records = {\n");
    inline for (comptime std.enums.values(records.Set)) |set| {
        const Element = set.Element();
        const element = comptime if (Element == []const u8) "string" else bind.noun(Element);
        try w.print("    {s}: {{ [number | string]: {s} }},\n", .{ @tagName(set), element });
    }
    try w.writeAll("}\n");

    try w.writeAll(
        \\
        \\-- The package `openreliant.core`.
        \\
        \\type Core = {
        \\    version: string,
        \\}
        \\
        \\-- The hooks (`openreliant.hooks`). Each handler gets `e`, whose class is named after the hook.
        \\
        \\declare class HookHandle
        \\    -- Removes the handler. Returns whether it was there.
        \\    function remove(self): boolean
        \\end
        \\
        \\-- The objects a handler is for: each test that's given must hold.
        \\type Filter = {
        \\    object: Object?,
        \\    type: (ShipType | { ShipType })?,
        \\    class: (ShipClass | { ShipClass })?,
        \\    side: (Side | { Side })?,
        \\}
        \\
    );
    comptime var declared: []const []const u8 = &.{};
    inline for (comptime std.enums.values(Hook)) |hook| {
        const class = comptime eventClass(hook);
        const seen = comptime for (declared) |name| {
            if (std.mem.eql(u8, name, class)) break true;
        } else false;
        if (!seen) {
            declared = declared ++ .{class};
            try writeEventClass(w, hook, class);
        }
    }
    try writeAdd(w, false);
    try writeAdd(w, true);
    try w.writeAll(
        \\type Hooks = {
        \\    -- Adds a handler that runs before the hook's function, or when its event happens.
        \\    add: HooksAdd,
        \\    -- Adds a handler that runs after the hook's function, which sees its result in e.result.
        \\    after: HooksAfter,
        \\}
        \\
    );

    try w.writeAll("\n-- What the engine tells the scripts.\n\n");
    try writeTable(w, "Mission", engine_hooks.Mission);
    try writeTable(w, "Outcome", engine_hooks.Outcome);
    try w.writeAll(
        \\
        \\-- What scripts return.
        \\
        \\type LoadScript = {
        \\    engine_handlers: {
        \\        on_records_loaded: (() -> ())?,
        \\    }?,
        \\}
        \\type GlobalScript = {
        \\    engine_handlers: {
        \\        on_init: (() -> ())?,
        \\        on_update: ((seconds: number) -> ())?,
        \\        on_step: (() -> ())?,
        \\        on_mission_start: ((mission: Mission) -> ())?,
        \\        on_mission_end: ((outcome: Outcome) -> ())?,
        \\        on_object_added: ((object: Object) -> ())?,
        \\        on_object_removed: ((object: Object) -> ())?,
        \\    }?,
        \\}
        \\
    );
}

/// Writes the class of `hook`'s `e`.
fn writeEventClass(w: *Writer, comptime hook: Hook, comptime class: []const u8) Writer.Error!void {
    const declared = comptime engine_hooks.declaration(hook);
    if (comptime engine_hooks.Fields(hook) == engine_hooks.RoutineFields) {
        try w.print("\n-- What a hook on one of the order table's routines sees.\ndeclare class {s}\n", .{class});
    } else {
        try w.print("\n-- {s}\ndeclare class {s}\n", .{ declared.about, class });
    }
    inline for (comptime values.shownFields(declared.Fields)) |field| try w.print("    {s}: {s}\n", .{ field.name, comptime luauType(field.type) });
    if (declared.Result != void) try w.print("    result: {s}\n", .{comptime luauType(declared.Result)});
    if (declared.on == .function) {
        const returned = comptime if (declared.Result == void) "()" else luauType(declared.Result) ++ "?";
        try w.print("    -- Runs the rest of the call now: the handlers after this one, then the function.\n    function original(self): {s}\n", .{returned});
    }
    try w.writeAll("end\n");
}

/// Writes the type of `hooks.add`, or of `hooks.after`, whose hooks are only the functions'.
fn writeAdd(w: *Writer, comptime functions_only: bool) Writer.Error!void {
    try w.print("\ntype Hooks{s} = ", .{if (functions_only) "After" else "Add"});
    var first = true;
    inline for (comptime std.enums.values(Hook)) |hook| {
        const declared = comptime engine_hooks.declaration(hook);
        if (functions_only and declared.on != .function) continue;
        const class = comptime eventClass(hook);
        const filter = if (declared.subject != null) "Filter | " else "";
        try w.print("{s}\n    ((name: \"{s}\", handler: (e: {s}) -> boolean?, filter: ({s}(e: {s}) -> boolean)?) -> HookHandle)", .{
            if (first) "" else " &", @tagName(hook), class, filter, class,
        });
        first = false;
    }
    try w.writeAll("\n");
}

/// Writes a table type of `T`'s fields, as `values.pushTable` gives them.
fn writeTable(w: *Writer, comptime name: []const u8, comptime T: type) Writer.Error!void {
    try w.print("type {s} = {{\n", .{name});
    inline for (comptime values.shownFields(T)) |field| try w.print("    {s}: {s},\n", .{ field.name, comptime luauType(field.type) });
    try w.writeAll("}\n");
}

/// Writes the reference page of the hooks, `docs/guide/hooks.md`: each hook with the fields of its
/// `e`, the fields of objects, and the names of values.
pub fn writeMarkdown(w: *Writer) Writer.Error!void {
    @setEvalBranchQuota(1_000_000);
    try w.writeAll(
        \\# Hooks
        \\
        \\This page lists everything mods' scripts can hook, with the fields each handler sees in `e`,
        \\then the fields of objects and the names of values. [Scripting](scripting.md#hooks) explains how
        \\to use them. `openreliant hooks` prints the same list, and `openreliant hooks <name>` one hook.
        \\
        \\This page is generated from OpenReliant's code by `make definitions`, so don't change it by hand.
        \\
        \\- [The game's functions](#the-games-functions)
        \\- [The order routines](#the-order-routines)
        \\- [The mission's events](#the-missions-events)
        \\- [The engine's events](#the-engines-events)
        \\- [Objects](#objects)
        \\- [Names of values](#names-of-values)
        \\
        \\## The game's functions
        \\
        \\Each is a function of the original game, under its name. `hooks.add` runs a handler before the
        \\function, and `hooks.after` runs one after it. Changing a field of `e` changes what the function
        \\does, and a handler that returns `false` stops it.
        \\
    );
    inline for (comptime std.enums.values(Hook)) |hook| {
        const declared = comptime engine_hooks.declaration(hook);
        if (declared.on == .function and engine_hooks.Fields(hook) != engine_hooks.RoutineFields) try writeHookSection(w, hook);
    }
    try w.writeAll(
        \\
        \\## The order routines
        \\
        \\Each order an object follows, such as Fight or Run Away, runs routines of the original game:
        \\an `init` as the order starts, an `update` each frame, and for a few an `exit` as it ends. Each
        \\routine is a hook under its name. Its handlers see the object that runs the order as `e.object`,
        \\and `e.object.order` is the order. Where OpenReliant doesn't run a routine yet, its handlers
        \\still run, and the function does nothing.
        \\
        \\| Hook | What it is |
        \\|---|---|
        \\
    );
    inline for (comptime std.enums.values(Hook)) |hook| {
        if (comptime engine_hooks.Fields(hook) == engine_hooks.RoutineFields) {
            try w.print("| `{s}` | {s} |\n", .{ @tagName(hook), comptime engine_hooks.declaration(hook).about });
        }
    }
    try w.writeAll(
        \\
        \\## The mission's events
        \\
        \\The events a mission's triggers can wait for, under the names of their conditions. Each comes
        \\for the mission's ships, those its file lists, whether or not a trigger waits for it. Their
        \\fields can only be read, and a handler that returns `false` stops the handlers after it.
        \\
    );
    inline for (comptime std.enums.values(Hook)) |hook| {
        if (comptime engine_hooks.declaration(hook).on == .mission_event) try writeHookSection(w, hook);
    }
    try w.writeAll(
        \\
        \\## The engine's events
        \\
        \\Their fields can only be read, and a handler that returns `false` stops the handlers after it.
        \\
    );
    inline for (comptime std.enums.values(Hook)) |hook| {
        if (comptime engine_hooks.declaration(hook).on == .engine_event) try writeHookSection(w, hook);
    }

    try w.writeAll(
        \\
        \\## Objects
        \\
        \\Scripts see objects through handles. A handle stays valid until its object is removed or its
        \\mission ends; reading a field of a handle that isn't valid is an error. These fields can only be
        \\read in this version.
        \\
        \\| Field | Type | What it is |
        \\|---|---|---|
        \\
    );
    inline for (comptime std.meta.declarations(objects.fields)) |decl| {
        const field = @field(objects.fields, decl.name);
        try w.print("| `{s}` | {s} | {s} |\n", .{ decl.name, comptime markdownType(field.Type), field.description });
    }
    inline for (comptime std.meta.declarations(objects.methods)) |decl| {
        try w.print("| `{s}()` | boolean | {s} |\n", .{ decl.name, @field(objects.methods, decl.name) });
    }

    try w.writeAll(
        \\
        \\## Names of values
        \\
        \\A value that has a name in OpenReliant is given as a string: its name. One without a name is a
        \\number. A script can set a field to either.
        \\
    );
    inline for (enums) |T| {
        try w.print("\n### {s}\n\n", .{comptime enumName(T)});
        inline for (comptime values.names(T), 0..) |name, at| try w.print("{s}`{s}`", .{ if (at == 0) "" else ", ", name });
        try w.writeAll(if (comptime values.takesNumbers(T)) ", or a number.\n" else ".\n");
    }
}

/// Writes the section of `hook` on the reference page.
fn writeHookSection(w: *Writer, comptime hook: Hook) Writer.Error!void {
    const declared = comptime engine_hooks.declaration(hook);
    try w.print("\n### {s}\n\n{s}\n\n", .{ @tagName(hook), declared.about });
    const fields = comptime values.shownFields(declared.Fields);
    if (fields.len == 0 and declared.Result == void) return;
    try w.writeAll("| Field | Type |\n|---|---|\n");
    inline for (fields) |field| try w.print("| `{s}` | {s} |\n", .{ field.name, comptime markdownType(field.type) });
    if (declared.Result != void) try w.print("| `result` | {s} |\n", .{comptime markdownType(declared.Result)});
}

/// A type on the reference page: its Luau type, with a link to the names of an enum's values.
fn markdownType(comptime T: type) []const u8 {
    comptime {
        const Plain = switch (@typeInfo(T)) {
            .optional => |optional| optional.child,
            else => T,
        };
        const optional = if (Plain == T) "" else ", or nil";
        if (Plain == Object) return "[object](#objects)" ++ optional;
        if (@typeInfo(Plain) == .@"enum") {
            const name = enumName(Plain);
            var anchor: []const u8 = "";
            for (name) |c| anchor = anchor ++ .{std.ascii.toLower(c)};
            return "[" ++ name ++ "](#" ++ anchor ++ ")" ++ optional;
        }
        return luauType(Plain) ++ optional;
    }
}

/// Writes the list of hooks `openreliant hooks` prints: every hook, or only the one named `only`.
/// Returns false if there's no hook of that name.
pub fn writeList(w: *Writer, only: ?[]const u8) Writer.Error!bool {
    @setEvalBranchQuota(1_000_000);
    var found = false;
    var last: ?engine_hooks.On = null;
    inline for (comptime std.enums.values(Hook)) |hook| {
        const declared = comptime engine_hooks.declaration(hook);
        const matches = if (only) |name| std.mem.eql(u8, name, @tagName(hook)) else true;
        if (matches) {
            found = true;
            if (only == null and last != declared.on) {
                if (last != null) try w.writeAll("\n");
                try w.writeAll(switch (declared.on) {
                    .function => "The game's functions. hooks.add runs a handler before the function, hooks.after after it.\n",
                    .mission_event => "The mission's events, for the mission's ships. Their fields can only be read.\n",
                    .engine_event => "The engine's events. Their fields can only be read.\n",
                });
                last = declared.on;
            }
            try w.print("\n{s}", .{@tagName(hook)});
            if (declared.address) |address| try w.print(" (0x{X:0>8})", .{address});
            try w.print("\n    {s}\n", .{declared.about});
            inline for (comptime values.shownFields(declared.Fields)) |field| {
                try w.print("    e.{s}: {s}", .{ field.name, comptime luauType(field.type) });
                try writeChoices(w, field.type);
                try w.writeAll("\n");
            }
            if (declared.Result != void) try w.print("    e.result: {s}\n", .{comptime luauType(declared.Result)});
        }
    }
    return found;
}

/// The most names of an enum's values that `openreliant hooks` lists after a field's type.
const listed_names = 12;

/// Writes the names a field's enum takes, where there are few.
fn writeChoices(w: *Writer, comptime T: type) Writer.Error!void {
    const Plain = switch (@typeInfo(T)) {
        .optional => |optional| optional.child,
        else => T,
    };
    if (comptime @typeInfo(Plain) != .@"enum" or Plain == Object) return;
    const names = comptime values.names(Plain);
    if (names.len > listed_names) return;
    try w.writeAll(" (");
    inline for (names, 0..) |name, at| try w.print("{s}\"{s}\"", .{ if (at == 0) "" else ", ", name });
    if (comptime values.takesNumbers(Plain)) try w.writeAll(", or a number");
    try w.writeAll(")");
}

test "the definitions don't change unless the scripting API does" {
    var buffer: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buffer.deinit();
    try writeDefinitions(&buffer.writer);
    const pinned = @embedFile("openreliant.d.luau");
    if (!std.mem.eql(u8, buffer.written(), pinned)) {
        std.debug.print("the scripting API has changed: if that's meant, run `make definitions` to update docs/guide/openreliant.d.luau\n", .{});
        return error.TestUnexpectedResult;
    }
}

test "the reference page doesn't change unless the scripting API does" {
    var buffer: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buffer.deinit();
    try writeMarkdown(&buffer.writer);
    const pinned = @embedFile("hooks.md");
    if (!std.mem.eql(u8, buffer.written(), pinned)) {
        std.debug.print("the scripting API has changed: if that's meant, run `make definitions` to update docs/guide/hooks.md\n", .{});
        return error.TestUnexpectedResult;
    }
}

test writeList {
    var buffer: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buffer.deinit();
    try std.testing.expect(try writeList(&buffer.writer, "object_damage"));
    try std.testing.expect(std.mem.indexOf(u8, buffer.written(), "e.quadrant: Quadrant (\"left\", \"right\", \"fore\", \"aft\")") != null);
    try std.testing.expect(!try writeList(&buffer.writer, "nothing"));
}
