//! The ITAC's tables: the shapes it lights where the pointer is over them, and the debriefings
//! its DEBRIEFINGS shows.
//!
//! Generated by `src/tools/tablegen` from the payload executable's lit shapes at 0x004E94D8, 40
//! rows, and its debriefings from 0x004E4A68, 5 tables of 28 rows. Do not edit by hand; run
//! `make itac-tables`.

/// A shape the ITAC lights where the pointer is over it, while a section its mask holds shows.
pub const LitShape = struct { at: [2]i16, shape: u16, sections: u32 };

pub const lit_shapes = [_]LitShape{
    .{ .at = .{ 16, 422 }, .shape = 0x24, .sections = 0xFFFFFFFF },
    .{ .at = .{ 86, 422 }, .shape = 0x25, .sections = 0xFFFFFFFF },
    .{ .at = .{ 156, 422 }, .shape = 0x26, .sections = 0xFFFFFFFF },
    .{ .at = .{ 226, 422 }, .shape = 0x27, .sections = 0xFFFFFFFF },
    .{ .at = .{ 296, 422 }, .shape = 0x28, .sections = 0xFFFFFFFF },
    .{ .at = .{ 366, 422 }, .shape = 0x29, .sections = 0xFFFFFFFF },
    .{ .at = .{ 436, 422 }, .shape = 0x2A, .sections = 0xFFFFFFFF },
    .{ .at = .{ 506, 422 }, .shape = 0x2B, .sections = 0xFFFFFFFF },
    .{ .at = .{ 576, 422 }, .shape = 0x2C, .sections = 0xFFFFFFFF },
    .{ .at = .{ 221, 322 }, .shape = 0x1F, .sections = 0x1 },
    .{ .at = .{ 246, 322 }, .shape = 0x20, .sections = 0x1 },
    .{ .at = .{ 516, 369 }, .shape = 0x1F, .sections = 0x1 },
    .{ .at = .{ 543, 369 }, .shape = 0x20, .sections = 0x1 },
    .{ .at = .{ 47, 328 }, .shape = 0x1F, .sections = 0x2 },
    .{ .at = .{ 73, 328 }, .shape = 0x20, .sections = 0x2 },
    .{ .at = .{ 516, 369 }, .shape = 0x1F, .sections = 0x2 },
    .{ .at = .{ 542, 369 }, .shape = 0x20, .sections = 0x2 },
    .{ .at = .{ 136, 283 }, .shape = 0x1F, .sections = 0x4 },
    .{ .at = .{ 162, 283 }, .shape = 0x20, .sections = 0x4 },
    .{ .at = .{ 517, 369 }, .shape = 0x1F, .sections = 0x4 },
    .{ .at = .{ 543, 369 }, .shape = 0x20, .sections = 0x4 },
    .{ .at = .{ 366, 277 }, .shape = 0x2D, .sections = 0x4 },
    .{ .at = .{ 517, 369 }, .shape = 0x1F, .sections = 0x8 },
    .{ .at = .{ 543, 369 }, .shape = 0x20, .sections = 0x8 },
    .{ .at = .{ 334, 206 }, .shape = 0x1F, .sections = 0x10 },
    .{ .at = .{ 360, 206 }, .shape = 0x20, .sections = 0x10 },
    .{ .at = .{ 517, 369 }, .shape = 0x1F, .sections = 0x10 },
    .{ .at = .{ 543, 369 }, .shape = 0x20, .sections = 0x10 },
    .{ .at = .{ 327, 216 }, .shape = 0x1F, .sections = 0x20 },
    .{ .at = .{ 353, 216 }, .shape = 0x20, .sections = 0x20 },
    .{ .at = .{ 517, 369 }, .shape = 0x1F, .sections = 0x20 },
    .{ .at = .{ 543, 369 }, .shape = 0x20, .sections = 0x20 },
    .{ .at = .{ 47, 343 }, .shape = 0x1F, .sections = 0x40 },
    .{ .at = .{ 73, 343 }, .shape = 0x20, .sections = 0x40 },
    .{ .at = .{ 517, 369 }, .shape = 0x1F, .sections = 0x40 },
    .{ .at = .{ 543, 369 }, .shape = 0x20, .sections = 0x40 },
    .{ .at = .{ 295, 379 }, .shape = 0x1F, .sections = 0x80 },
    .{ .at = .{ 321, 379 }, .shape = 0x20, .sections = 0x80 },
    .{ .at = .{ 478, 59 }, .shape = 0x21, .sections = 0x78 },
    .{ .at = .{ 551, 59 }, .shape = 0x22, .sections = 0x78 },
};

/// A debriefing: the string that heads it, and those of its paragraphs.
pub const Text = struct { header: u16, paragraphs: []const u16 };

/// By the rating, failure (0) to success with its bonus (4), then by the mission number less one.
pub const debriefings = [5][28]Text{
    .{ // failure
        .{ .header = 10, .paragraphs = &.{ 364, 365, 366, 367, 368 } }, // 1
        .{ .header = 10, .paragraphs = &.{ 247, 248, 249, 250 } }, // 2
        .{ .header = 10, .paragraphs = &.{ 389, 390, 391, 392, 393, 394 } }, // 3
        .{ .header = 10, .paragraphs = &.{ 260, 261, 262, 263, 264 } }, // 4
        .{ .header = 10, .paragraphs = &.{ 412, 413, 414, 415, 416, 417, 418 } }, // 5
        .{ .header = 10, .paragraphs = &.{ 200, 201, 202, 203, 204 } }, // 6
        .{ .header = 10, .paragraphs = &.{ 1665, 1666, 1667, 1668, 1669 } }, // 7
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 8
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 9
        .{ .header = 10, .paragraphs = &.{ 1693, 1694, 1695, 1696, 1697 } }, // 10
        .{ .header = 10, .paragraphs = &.{ 1862, 1863, 1864, 1865 } }, // 11
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 12
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 13
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 14
        .{ .header = 10, .paragraphs = &.{ 276, 277, 278, 279, 280 } }, // 15
        .{ .header = 10, .paragraphs = &.{ 1785, 1786, 1787 } }, // 16
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 17
        .{ .header = 10, .paragraphs = &.{ 1800, 1801, 1802, 1803 } }, // 18
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 19
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 20
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 21
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 22
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 23
        .{ .header = 10, .paragraphs = &.{ 1853, 1854, 1855 } }, // 24
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 25
        .{ .header = 10, .paragraphs = &.{ 1879, 1880, 1881 } }, // 26
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 27
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 28
    },
    .{ // partial failure
        .{ .header = 10, .paragraphs = &.{ 360, 361, 362, 363 } }, // 1
        .{ .header = 10, .paragraphs = &.{ 1774, 1775 } }, // 2
        .{ .header = 10, .paragraphs = &.{ 383, 384, 385, 386, 387, 388 } }, // 3
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 4
        .{ .header = 10, .paragraphs = &.{ 406, 407, 408, 409, 410, 411 } }, // 5
        .{ .header = 10, .paragraphs = &.{ 195, 196, 197, 198, 199 } }, // 6
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 7
        .{ .header = 10, .paragraphs = &.{ 295, 296, 297, 298 } }, // 8
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 9
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 10
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 11
        .{ .header = 10, .paragraphs = &.{ 311, 312, 313, 314, 315 } }, // 12
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 13
        .{ .header = 10, .paragraphs = &.{ 1712, 1713, 1714, 1715 } }, // 14
        .{ .header = 10, .paragraphs = &.{ 273, 274, 275 } }, // 15
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 16
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 17
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 18
        .{ .header = 10, .paragraphs = &.{ 1831, 1832, 1833 } }, // 19
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 20
        .{ .header = 10, .paragraphs = &.{ 1796, 1797, 1798, 1799 } }, // 21
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 22
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 23
        .{ .header = 10, .paragraphs = &.{ 1851, 1852 } }, // 24
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 25
        .{ .header = 10, .paragraphs = &.{ 1876, 1877, 1878 } }, // 26
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 27
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 28
    },
    .{ // partial success
        .{ .header = 10, .paragraphs = &.{ 356, 357, 358, 359 } }, // 1
        .{ .header = 10, .paragraphs = &.{ 244, 245, 246 } }, // 2
        .{ .header = 10, .paragraphs = &.{ 378, 380, 381, 382 } }, // 3
        .{ .header = 10, .paragraphs = &.{ 255, 256, 257, 258, 259 } }, // 4
        .{ .header = 10, .paragraphs = &.{ 400, 401, 402, 403, 404, 405 } }, // 5
        .{ .header = 10, .paragraphs = &.{ 190, 191, 192, 193, 194 } }, // 6
        .{ .header = 10, .paragraphs = &.{ 1661, 1662, 1663, 1664 } }, // 7
        .{ .header = 10, .paragraphs = &.{ 290, 291, 292, 293, 294 } }, // 8
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 9
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 10
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 11
        .{ .header = 10, .paragraphs = &.{ 308, 309, 310 } }, // 12
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 13
        .{ .header = 10, .paragraphs = &.{ 1708, 1710, 1711 } }, // 14
        .{ .header = 10, .paragraphs = &.{ 269, 270, 271, 272 } }, // 15
        .{ .header = 10, .paragraphs = &.{ 1782, 1783, 1784 } }, // 16
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 17
        .{ .header = 10, .paragraphs = &.{ 1792, 1793, 1794, 1795 } }, // 18
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 19
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 20
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 21
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 22
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 23
        .{ .header = 10, .paragraphs = &.{ 1848, 1849, 1850 } }, // 24
        .{ .header = 10, .paragraphs = &.{ 1842, 1843, 1844 } }, // 25
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 26
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 27
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 28
    },
    .{ // success
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14 } }, // 1
        .{ .header = 10, .paragraphs = &.{ 241, 242, 243 } }, // 2
        .{ .header = 10, .paragraphs = &.{ 373, 374, 375, 376, 377 } }, // 3
        .{ .header = 10, .paragraphs = &.{ 251, 252, 253, 254 } }, // 4
        .{ .header = 10, .paragraphs = &.{ 395, 396, 397, 398, 399 } }, // 5
        .{ .header = 10, .paragraphs = &.{ 186, 187, 188, 189 } }, // 6
        .{ .header = 10, .paragraphs = &.{ 1657, 1658, 1659, 1660 } }, // 7
        .{ .header = 10, .paragraphs = &.{ 286, 287, 288, 289 } }, // 8
        .{ .header = 10, .paragraphs = &.{ 1676, 1677, 1678, 1679, 1680, 1681 } }, // 9
        .{ .header = 10, .paragraphs = &.{ 1688, 1689, 1690, 1691, 1692 } }, // 10
        .{ .header = 10, .paragraphs = &.{ 1859, 1860, 1861 } }, // 11
        .{ .header = 10, .paragraphs = &.{ 304, 305, 306, 307 } }, // 12
        .{ .header = 10, .paragraphs = &.{ 265, 266, 267, 268 } }, // 13
        .{ .header = 10, .paragraphs = &.{ 1703, 1704, 1705, 1706, 1707 } }, // 14
        .{ .header = 10, .paragraphs = &.{ 265, 266, 267, 268 } }, // 15
        .{ .header = 10, .paragraphs = &.{ 1779, 1780, 1781 } }, // 16
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 17
        .{ .header = 10, .paragraphs = &.{ 1788, 1789, 1790, 1791 } }, // 18
        .{ .header = 10, .paragraphs = &.{ 1826, 1827, 1828, 1829, 1830 } }, // 19
        .{ .header = 10, .paragraphs = &.{ 1834, 1835 } }, // 20
        .{ .header = 10, .paragraphs = &.{ 1807, 1808 } }, // 21
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 22
        .{ .header = 10, .paragraphs = &.{ 1869, 1870 } }, // 23
        .{ .header = 10, .paragraphs = &.{ 1845, 1846, 1847 } }, // 24
        .{ .header = 10, .paragraphs = &.{ 1839, 1840, 1841 } }, // 25
        .{ .header = 10, .paragraphs = &.{ 1873, 1874, 1875 } }, // 26
        .{ .header = 10, .paragraphs = &.{ 1886, 1887, 1888, 1889 } }, // 27
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 28
    },
    .{ // success with its bonus
        .{ .header = 10, .paragraphs = &.{ 1641, 1642, 1643, 1644, 1645 } }, // 1
        .{ .header = 10, .paragraphs = &.{ 1770, 1771, 1772, 1773 } }, // 2
        .{ .header = 10, .paragraphs = &.{ 369, 370, 371, 372 } }, // 3
        .{ .header = 10, .paragraphs = &.{ 1646, 1647, 1648, 1649, 1650 } }, // 4
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 5
        .{ .header = 10, .paragraphs = &.{ 181, 182, 183, 184, 185 } }, // 6
        .{ .header = 10, .paragraphs = &.{ 1651, 1652, 1653, 1654, 1655, 1656 } }, // 7
        .{ .header = 10, .paragraphs = &.{ 281, 282, 283, 284, 285 } }, // 8
        .{ .header = 10, .paragraphs = &.{ 1670, 1671, 1672, 1673, 1674, 1675 } }, // 9
        .{ .header = 10, .paragraphs = &.{ 1682, 1683, 1684, 1685, 1686, 1687 } }, // 10
        .{ .header = 10, .paragraphs = &.{ 1856, 1857, 1858 } }, // 11
        .{ .header = 10, .paragraphs = &.{ 299, 300, 301, 302, 303 } }, // 12
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 13
        .{ .header = 10, .paragraphs = &.{ 1698, 1699, 1700, 1701, 1702 } }, // 14
        .{ .header = 10, .paragraphs = &.{ 276, 277, 278, 279, 280 } }, // 15
        .{ .header = 10, .paragraphs = &.{ 1776, 1777, 1778 } }, // 16
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 17
        .{ .header = 10, .paragraphs = &.{ 1819, 1820, 1821, 1822, 1823 } }, // 18
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 19
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 20
        .{ .header = 10, .paragraphs = &.{ 1804, 1805, 1806 } }, // 21
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 22
        .{ .header = 10, .paragraphs = &.{ 1866, 1867, 1868 } }, // 23
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 24
        .{ .header = 10, .paragraphs = &.{ 1836, 1837, 1838 } }, // 25
        .{ .header = 10, .paragraphs = &.{ 1871, 1872 } }, // 26
        .{ .header = 10, .paragraphs = &.{ 1882, 1883, 1884, 1885 } }, // 27
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 28
    },
};
