//! The ITAC's tables: the shapes it lights where the pointer is over them, the debriefings its
//! DEBRIEFINGS shows, the items of its NEWS REPORTS, the reports of its VIDEO REPORTS, the
//! fighters, capital ships, squadrons and personnel of either side, and the pilots of its
//! KILLBOARD.
//!
//! Generated by `src/tools/tablegen` from the payload executable's lit shapes at 0x004E94D8, 40
//! rows, its debriefings from 0x004E4A68, 5 tables of 28 rows, its news items at 0x004EB0E8,
//! 24 rows, its video reports at 0x004EE5B0, 6 rows, its fighters at 0x004E5470, its capital
//! ships at 0x004E42C0, its squadrons at 0x004EBD10 and 0x004EBF28, its personnel at 0x004EB430 and
//! its pilots at 0x004E9A08, 19 rows. Do not edit by hand; run `make itac-tables`.

/// A shape the ITAC lights where the pointer is over it, while a section its mask holds shows.
pub const LitShape = struct { at: [2]i16, shape: u16, sections: u32 };

pub const lit_shapes = [_]LitShape{
    .{ .at = .{ 16, 422 }, .shape = 0x24, .sections = 0xFFFFFFFF },
    .{ .at = .{ 86, 422 }, .shape = 0x25, .sections = 0xFFFFFFFF },
    .{ .at = .{ 156, 422 }, .shape = 0x26, .sections = 0xFFFFFFFF },
    .{ .at = .{ 226, 422 }, .shape = 0x27, .sections = 0xFFFFFFFF },
    .{ .at = .{ 296, 422 }, .shape = 0x28, .sections = 0xFFFFFFFF },
    .{ .at = .{ 366, 422 }, .shape = 0x29, .sections = 0xFFFFFFFF },
    .{ .at = .{ 436, 422 }, .shape = 0x2A, .sections = 0xFFFFFFFF },
    .{ .at = .{ 506, 422 }, .shape = 0x2B, .sections = 0xFFFFFFFF },
    .{ .at = .{ 576, 422 }, .shape = 0x2C, .sections = 0xFFFFFFFF },
    .{ .at = .{ 221, 322 }, .shape = 0x1F, .sections = 0x1 },
    .{ .at = .{ 246, 322 }, .shape = 0x20, .sections = 0x1 },
    .{ .at = .{ 516, 369 }, .shape = 0x1F, .sections = 0x1 },
    .{ .at = .{ 543, 369 }, .shape = 0x20, .sections = 0x1 },
    .{ .at = .{ 47, 328 }, .shape = 0x1F, .sections = 0x2 },
    .{ .at = .{ 73, 328 }, .shape = 0x20, .sections = 0x2 },
    .{ .at = .{ 516, 369 }, .shape = 0x1F, .sections = 0x2 },
    .{ .at = .{ 542, 369 }, .shape = 0x20, .sections = 0x2 },
    .{ .at = .{ 136, 283 }, .shape = 0x1F, .sections = 0x4 },
    .{ .at = .{ 162, 283 }, .shape = 0x20, .sections = 0x4 },
    .{ .at = .{ 517, 369 }, .shape = 0x1F, .sections = 0x4 },
    .{ .at = .{ 543, 369 }, .shape = 0x20, .sections = 0x4 },
    .{ .at = .{ 366, 277 }, .shape = 0x2D, .sections = 0x4 },
    .{ .at = .{ 517, 369 }, .shape = 0x1F, .sections = 0x8 },
    .{ .at = .{ 543, 369 }, .shape = 0x20, .sections = 0x8 },
    .{ .at = .{ 334, 206 }, .shape = 0x1F, .sections = 0x10 },
    .{ .at = .{ 360, 206 }, .shape = 0x20, .sections = 0x10 },
    .{ .at = .{ 517, 369 }, .shape = 0x1F, .sections = 0x10 },
    .{ .at = .{ 543, 369 }, .shape = 0x20, .sections = 0x10 },
    .{ .at = .{ 327, 216 }, .shape = 0x1F, .sections = 0x20 },
    .{ .at = .{ 353, 216 }, .shape = 0x20, .sections = 0x20 },
    .{ .at = .{ 517, 369 }, .shape = 0x1F, .sections = 0x20 },
    .{ .at = .{ 543, 369 }, .shape = 0x20, .sections = 0x20 },
    .{ .at = .{ 47, 343 }, .shape = 0x1F, .sections = 0x40 },
    .{ .at = .{ 73, 343 }, .shape = 0x20, .sections = 0x40 },
    .{ .at = .{ 517, 369 }, .shape = 0x1F, .sections = 0x40 },
    .{ .at = .{ 543, 369 }, .shape = 0x20, .sections = 0x40 },
    .{ .at = .{ 295, 379 }, .shape = 0x1F, .sections = 0x80 },
    .{ .at = .{ 321, 379 }, .shape = 0x20, .sections = 0x80 },
    .{ .at = .{ 478, 59 }, .shape = 0x21, .sections = 0x78 },
    .{ .at = .{ 551, 59 }, .shape = 0x22, .sections = 0x78 },
};

/// A debriefing: the string that heads it, and those of its paragraphs.
pub const Text = struct { header: u16, paragraphs: []const u16 };

/// By the rating, failure (0) to success with its bonus (4), then by the mission number less one.
pub const debriefings = [5][28]Text{
    .{ // failure
        .{ .header = 10, .paragraphs = &.{ 364, 365, 366, 367, 368 } }, // 1
        .{ .header = 10, .paragraphs = &.{ 247, 248, 249, 250 } }, // 2
        .{ .header = 10, .paragraphs = &.{ 389, 390, 391, 392, 393, 394 } }, // 3
        .{ .header = 10, .paragraphs = &.{ 260, 261, 262, 263, 264 } }, // 4
        .{ .header = 10, .paragraphs = &.{ 412, 413, 414, 415, 416, 417, 418 } }, // 5
        .{ .header = 10, .paragraphs = &.{ 200, 201, 202, 203, 204 } }, // 6
        .{ .header = 10, .paragraphs = &.{ 1665, 1666, 1667, 1668, 1669 } }, // 7
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 8
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 9
        .{ .header = 10, .paragraphs = &.{ 1693, 1694, 1695, 1696, 1697 } }, // 10
        .{ .header = 10, .paragraphs = &.{ 1862, 1863, 1864, 1865 } }, // 11
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 12
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 13
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 14
        .{ .header = 10, .paragraphs = &.{ 276, 277, 278, 279, 280 } }, // 15
        .{ .header = 10, .paragraphs = &.{ 1785, 1786, 1787 } }, // 16
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 17
        .{ .header = 10, .paragraphs = &.{ 1800, 1801, 1802, 1803 } }, // 18
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 19
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 20
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 21
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 22
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 23
        .{ .header = 10, .paragraphs = &.{ 1853, 1854, 1855 } }, // 24
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 25
        .{ .header = 10, .paragraphs = &.{ 1879, 1880, 1881 } }, // 26
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 27
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 28
    },
    .{ // partial failure
        .{ .header = 10, .paragraphs = &.{ 360, 361, 362, 363 } }, // 1
        .{ .header = 10, .paragraphs = &.{ 1774, 1775 } }, // 2
        .{ .header = 10, .paragraphs = &.{ 383, 384, 385, 386, 387, 388 } }, // 3
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 4
        .{ .header = 10, .paragraphs = &.{ 406, 407, 408, 409, 410, 411 } }, // 5
        .{ .header = 10, .paragraphs = &.{ 195, 196, 197, 198, 199 } }, // 6
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 7
        .{ .header = 10, .paragraphs = &.{ 295, 296, 297, 298 } }, // 8
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 9
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 10
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 11
        .{ .header = 10, .paragraphs = &.{ 311, 312, 313, 314, 315 } }, // 12
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 13
        .{ .header = 10, .paragraphs = &.{ 1712, 1713, 1714, 1715 } }, // 14
        .{ .header = 10, .paragraphs = &.{ 273, 274, 275 } }, // 15
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 16
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 17
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 18
        .{ .header = 10, .paragraphs = &.{ 1831, 1832, 1833 } }, // 19
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 20
        .{ .header = 10, .paragraphs = &.{ 1796, 1797, 1798, 1799 } }, // 21
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 22
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 23
        .{ .header = 10, .paragraphs = &.{ 1851, 1852 } }, // 24
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 25
        .{ .header = 10, .paragraphs = &.{ 1876, 1877, 1878 } }, // 26
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 27
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 28
    },
    .{ // partial success
        .{ .header = 10, .paragraphs = &.{ 356, 357, 358, 359 } }, // 1
        .{ .header = 10, .paragraphs = &.{ 244, 245, 246 } }, // 2
        .{ .header = 10, .paragraphs = &.{ 378, 380, 381, 382 } }, // 3
        .{ .header = 10, .paragraphs = &.{ 255, 256, 257, 258, 259 } }, // 4
        .{ .header = 10, .paragraphs = &.{ 400, 401, 402, 403, 404, 405 } }, // 5
        .{ .header = 10, .paragraphs = &.{ 190, 191, 192, 193, 194 } }, // 6
        .{ .header = 10, .paragraphs = &.{ 1661, 1662, 1663, 1664 } }, // 7
        .{ .header = 10, .paragraphs = &.{ 290, 291, 292, 293, 294 } }, // 8
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 9
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 10
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 11
        .{ .header = 10, .paragraphs = &.{ 308, 309, 310 } }, // 12
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 13
        .{ .header = 10, .paragraphs = &.{ 1708, 1710, 1711 } }, // 14
        .{ .header = 10, .paragraphs = &.{ 269, 270, 271, 272 } }, // 15
        .{ .header = 10, .paragraphs = &.{ 1782, 1783, 1784 } }, // 16
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 17
        .{ .header = 10, .paragraphs = &.{ 1792, 1793, 1794, 1795 } }, // 18
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 19
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 20
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 21
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 22
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 23
        .{ .header = 10, .paragraphs = &.{ 1848, 1849, 1850 } }, // 24
        .{ .header = 10, .paragraphs = &.{ 1842, 1843, 1844 } }, // 25
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 26
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 27
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 28
    },
    .{ // success
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14 } }, // 1
        .{ .header = 10, .paragraphs = &.{ 241, 242, 243 } }, // 2
        .{ .header = 10, .paragraphs = &.{ 373, 374, 375, 376, 377 } }, // 3
        .{ .header = 10, .paragraphs = &.{ 251, 252, 253, 254 } }, // 4
        .{ .header = 10, .paragraphs = &.{ 395, 396, 397, 398, 399 } }, // 5
        .{ .header = 10, .paragraphs = &.{ 186, 187, 188, 189 } }, // 6
        .{ .header = 10, .paragraphs = &.{ 1657, 1658, 1659, 1660 } }, // 7
        .{ .header = 10, .paragraphs = &.{ 286, 287, 288, 289 } }, // 8
        .{ .header = 10, .paragraphs = &.{ 1676, 1677, 1678, 1679, 1680, 1681 } }, // 9
        .{ .header = 10, .paragraphs = &.{ 1688, 1689, 1690, 1691, 1692 } }, // 10
        .{ .header = 10, .paragraphs = &.{ 1859, 1860, 1861 } }, // 11
        .{ .header = 10, .paragraphs = &.{ 304, 305, 306, 307 } }, // 12
        .{ .header = 10, .paragraphs = &.{ 265, 266, 267, 268 } }, // 13
        .{ .header = 10, .paragraphs = &.{ 1703, 1704, 1705, 1706, 1707 } }, // 14
        .{ .header = 10, .paragraphs = &.{ 265, 266, 267, 268 } }, // 15
        .{ .header = 10, .paragraphs = &.{ 1779, 1780, 1781 } }, // 16
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 17
        .{ .header = 10, .paragraphs = &.{ 1788, 1789, 1790, 1791 } }, // 18
        .{ .header = 10, .paragraphs = &.{ 1826, 1827, 1828, 1829, 1830 } }, // 19
        .{ .header = 10, .paragraphs = &.{ 1834, 1835 } }, // 20
        .{ .header = 10, .paragraphs = &.{ 1807, 1808 } }, // 21
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 22
        .{ .header = 10, .paragraphs = &.{ 1869, 1870 } }, // 23
        .{ .header = 10, .paragraphs = &.{ 1845, 1846, 1847 } }, // 24
        .{ .header = 10, .paragraphs = &.{ 1839, 1840, 1841 } }, // 25
        .{ .header = 10, .paragraphs = &.{ 1873, 1874, 1875 } }, // 26
        .{ .header = 10, .paragraphs = &.{ 1886, 1887, 1888, 1889 } }, // 27
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 28
    },
    .{ // success with its bonus
        .{ .header = 10, .paragraphs = &.{ 1641, 1642, 1643, 1644, 1645 } }, // 1
        .{ .header = 10, .paragraphs = &.{ 1770, 1771, 1772, 1773 } }, // 2
        .{ .header = 10, .paragraphs = &.{ 369, 370, 371, 372 } }, // 3
        .{ .header = 10, .paragraphs = &.{ 1646, 1647, 1648, 1649, 1650 } }, // 4
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 5
        .{ .header = 10, .paragraphs = &.{ 181, 182, 183, 184, 185 } }, // 6
        .{ .header = 10, .paragraphs = &.{ 1651, 1652, 1653, 1654, 1655, 1656 } }, // 7
        .{ .header = 10, .paragraphs = &.{ 281, 282, 283, 284, 285 } }, // 8
        .{ .header = 10, .paragraphs = &.{ 1670, 1671, 1672, 1673, 1674, 1675 } }, // 9
        .{ .header = 10, .paragraphs = &.{ 1682, 1683, 1684, 1685, 1686, 1687 } }, // 10
        .{ .header = 10, .paragraphs = &.{ 1856, 1857, 1858 } }, // 11
        .{ .header = 10, .paragraphs = &.{ 299, 300, 301, 302, 303 } }, // 12
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 13
        .{ .header = 10, .paragraphs = &.{ 1698, 1699, 1700, 1701, 1702 } }, // 14
        .{ .header = 10, .paragraphs = &.{ 276, 277, 278, 279, 280 } }, // 15
        .{ .header = 10, .paragraphs = &.{ 1776, 1777, 1778 } }, // 16
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 17
        .{ .header = 10, .paragraphs = &.{ 1819, 1820, 1821, 1822, 1823 } }, // 18
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 19
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 20
        .{ .header = 10, .paragraphs = &.{ 1804, 1805, 1806 } }, // 21
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 22
        .{ .header = 10, .paragraphs = &.{ 1866, 1867, 1868 } }, // 23
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 24
        .{ .header = 10, .paragraphs = &.{ 1836, 1837, 1838 } }, // 25
        .{ .header = 10, .paragraphs = &.{ 1871, 1872 } }, // 26
        .{ .header = 10, .paragraphs = &.{ 1882, 1883, 1884, 1885 } }, // 27
        .{ .header = 10, .paragraphs = &.{ 11, 12, 13, 14, 15 } }, // 28
    },
};

/// A news item: the string of its title, those of its paragraphs, the shape of its picture in
/// `newsrep.spr`, and the mission after which it is listed.
pub const NewsItem = struct { title: u16, paragraphs: []const u16, shape: u16, mission: i32 };

pub const news = [_]NewsItem{
    .{ .title = 537, .paragraphs = &.{ 565, 566, 567, 568 }, .shape = 1, .mission = 0 },
    .{ .title = 538, .paragraphs = &.{ 569, 570, 571 }, .shape = 2, .mission = 1 },
    .{ .title = 539, .paragraphs = &.{ 572, 573, 574 }, .shape = 3, .mission = 2 },
    .{ .title = 540, .paragraphs = &.{ 575, 576, 577 }, .shape = 4, .mission = 3 },
    .{ .title = 541, .paragraphs = &.{ 578, 579, 580 }, .shape = 5, .mission = 4 },
    .{ .title = 542, .paragraphs = &.{ 581, 582 }, .shape = 6, .mission = 5 },
    .{ .title = 543, .paragraphs = &.{ 583, 584 }, .shape = 7, .mission = 6 },
    .{ .title = 544, .paragraphs = &.{ 585, 586 }, .shape = 8, .mission = 7 },
    .{ .title = 545, .paragraphs = &.{ 587, 588, 589 }, .shape = 9, .mission = 8 },
    .{ .title = 546, .paragraphs = &.{ 590, 591, 592 }, .shape = 10, .mission = 9 },
    .{ .title = 547, .paragraphs = &.{ 593, 594 }, .shape = 11, .mission = 10 },
    .{ .title = 550, .paragraphs = &.{ 601, 602 }, .shape = 15, .mission = 13 },
    .{ .title = 551, .paragraphs = &.{ 603, 604 }, .shape = 16, .mission = 14 },
    .{ .title = 552, .paragraphs = &.{ 605, 606 }, .shape = 17, .mission = 15 },
    .{ .title = 554, .paragraphs = &.{ 610, 611 }, .shape = 19, .mission = 17 },
    .{ .title = 555, .paragraphs = &.{ 612, 613 }, .shape = 20, .mission = 18 },
    .{ .title = 556, .paragraphs = &.{ 614, 615, 616 }, .shape = 21, .mission = 19 },
    .{ .title = 557, .paragraphs = &.{ 617, 618, 619 }, .shape = 22, .mission = 20 },
    .{ .title = 559, .paragraphs = &.{ 622, 623 }, .shape = 24, .mission = 22 },
    .{ .title = 560, .paragraphs = &.{ 624, 625, 626 }, .shape = 25, .mission = 23 },
    .{ .title = 561, .paragraphs = &.{ 627, 628 }, .shape = 27, .mission = 24 },
    .{ .title = 562, .paragraphs = &.{ 629, 630, 631 }, .shape = 28, .mission = 25 },
    .{ .title = 563, .paragraphs = &.{ 632, 633, 634 }, .shape = 29, .mission = 26 },
    .{ .title = 564, .paragraphs = &.{ 635, 636, 637 }, .shape = 30, .mission = 27 },
};

/// A video report: the string of its title, those of its paragraphs, the shape of its still in
/// `vidrep.spr`, the mission after which it is listed, its movie in the discs' archives, and the
/// part of the campaign it comes from, 1 for the Reliant's and 2 for the Yamato's.
pub const VideoItem = struct { title: u16, paragraphs: []const u16, shape: u16, mission: i32, movie: []const u8, part: u16 };

pub const videos = [_]VideoItem{
    .{ .title = 734, .paragraphs = &.{ 704, 705 }, .shape = 29, .mission = 0, .movie = "new_intro.bik", .part = 1 },
    .{ .title = 735, .paragraphs = &.{ 652, 653 }, .shape = 30, .mission = 7, .movie = "new_chapter1.bik", .part = 1 },
    .{ .title = 736, .paragraphs = &.{ 664, 665 }, .shape = 31, .mission = 13, .movie = "new_chapter2.bik", .part = 1 },
    .{ .title = 737, .paragraphs = &.{ 676, 677 }, .shape = 32, .mission = 18, .movie = "foster.bik", .part = 1 },
    .{ .title = 738, .paragraphs = &.{ 680, 681 }, .shape = 33, .mission = 19, .movie = "new_chapter3.bik", .part = 2 },
    .{ .title = 739, .paragraphs = &.{ 686, 687 }, .shape = 34, .mission = 21, .movie = "new_chapter4.bik", .part = 2 },
};

/// A gun a fighter carries: its string, and how many, 0 where the ITAC writes no count.
pub const Gun = struct { name: u16, count: i16 };

/// A fighter the ITAC lists, which the loadout offers too: the strings of its name, its type and
/// its clearance (0 for none), its crew, its guns, the strings of its special abilities, the shape
/// of its picture in `fighters.spr` (-1 for none), and its ship type.
pub const Fighter = struct { name: u16, type: u16, clearance: u16, crew: i16, guns: []const Gun, specials: []const u16, shape: i32, ship_type: u8 };

/// By side, the Alliance's first.
pub const fighters = [2][]const Fighter{
    &.{ // alliance
        .{ .name = 1035, .type = 1219, .clearance = 1224, .crew = 2, .guns = &.{ .{ .name = 1242, .count = 2 }, .{ .name = 1235, .count = 0 } }, .specials = &.{1251}, .shape = 1, .ship_type = 4 },
        .{ .name = 1025, .type = 1218, .clearance = 1223, .crew = 2, .guns = &.{.{ .name = 1240, .count = 2 }}, .specials = &.{1252}, .shape = 2, .ship_type = 3 },
        .{ .name = 1015, .type = 1219, .clearance = 1223, .crew = 3, .guns = &.{ .{ .name = 1237, .count = 2 }, .{ .name = 1238, .count = 0 }, .{ .name = 1239, .count = 0 } }, .specials = &.{}, .shape = 3, .ship_type = 2 },
        .{ .name = 1045, .type = 1219, .clearance = 1225, .crew = 2, .guns = &.{ .{ .name = 1241, .count = 0 }, .{ .name = 1243, .count = 2 } }, .specials = &.{}, .shape = 4, .ship_type = 5 },
        .{ .name = 1005, .type = 1218, .clearance = 1223, .crew = 2, .guns = &.{.{ .name = 1236, .count = 2 }}, .specials = &.{1252}, .shape = 6, .ship_type = 1 },
        .{ .name = 1065, .type = 1219, .clearance = 1227, .crew = 2, .guns = &.{ .{ .name = 1244, .count = 2 }, .{ .name = 1242, .count = 2 }, .{ .name = 1235, .count = 0 } }, .specials = &.{1251}, .shape = 7, .ship_type = 7 },
        .{ .name = 1105, .type = 1222, .clearance = 1231, .crew = 2, .guns = &.{ .{ .name = 1240, .count = 2 }, .{ .name = 1236, .count = 2 }, .{ .name = 1250, .count = 0 } }, .specials = &.{ 1251, 1253, 1256 }, .shape = 8, .ship_type = 11 },
        .{ .name = 995, .type = 1218, .clearance = 1223, .crew = 2, .guns = &.{ .{ .name = 1242, .count = 2 }, .{ .name = 1235, .count = 0 } }, .specials = &.{1251}, .shape = 9, .ship_type = 0 },
        .{ .name = 1085, .type = 1220, .clearance = 1229, .crew = 3, .guns = &.{ .{ .name = 1240, .count = 2 }, .{ .name = 1931, .count = 2 }, .{ .name = 1248, .count = 0 } }, .specials = &.{1251}, .shape = 11, .ship_type = 9 },
        .{ .name = 1095, .type = 1221, .clearance = 1230, .crew = 2, .guns = &.{.{ .name = 1242, .count = 2 }}, .specials = &.{ 1255, 1252, 1253, 1251 }, .shape = 13, .ship_type = 10 },
        .{ .name = 1055, .type = 1220, .clearance = 1226, .crew = 2, .guns = &.{ .{ .name = 1244, .count = 2 }, .{ .name = 1236, .count = 2 }, .{ .name = 1239, .count = 0 } }, .specials = &.{1252}, .shape = 14, .ship_type = 6 },
        .{ .name = 1075, .type = 1220, .clearance = 1228, .crew = 3, .guns = &.{ .{ .name = 1246, .count = 2 }, .{ .name = 1249, .count = 2 }, .{ .name = 1247, .count = 1 }, .{ .name = 1239, .count = 0 } }, .specials = &.{1253}, .shape = 16, .ship_type = 8 },
    },
    &.{ // coalition
        .{ .name = 1185, .type = 1218, .clearance = 0, .crew = 1, .guns = &.{ .{ .name = 1236, .count = 2 }, .{ .name = 1243, .count = 2 } }, .specials = &.{}, .shape = 23, .ship_type = 42 },
        .{ .name = 1175, .type = 1222, .clearance = 0, .crew = 2, .guns = &.{ .{ .name = 1240, .count = 2 }, .{ .name = 1243, .count = 2 }, .{ .name = 1258, .count = 2 } }, .specials = &.{}, .shape = 24, .ship_type = 49 },
        .{ .name = 1135, .type = 1219, .clearance = 0, .crew = 2, .guns = &.{ .{ .name = 1240, .count = 2 }, .{ .name = 1238, .count = 0 }, .{ .name = 1259, .count = 0 } }, .specials = &.{}, .shape = 25, .ship_type = 39 },
        .{ .name = 1125, .type = 1219, .clearance = 0, .crew = 2, .guns = &.{ .{ .name = 1244, .count = 2 }, .{ .name = 1242, .count = 2 }, .{ .name = 1258, .count = 0 } }, .specials = &.{}, .shape = 26, .ship_type = 40 },
        .{ .name = 1115, .type = 1220, .clearance = 0, .crew = 3, .guns = &.{ .{ .name = 1246, .count = 2 }, .{ .name = 1240, .count = 2 }, .{ .name = 1257, .count = 0 } }, .specials = &.{}, .shape = 18, .ship_type = 50 },
        .{ .name = 1145, .type = 1219, .clearance = 0, .crew = 2, .guns = &.{ .{ .name = 1240, .count = 2 }, .{ .name = 1242, .count = 2 }, .{ .name = 1249, .count = 2 }, .{ .name = 1260, .count = 0 } }, .specials = &.{}, .shape = 19, .ship_type = 44 },
        .{ .name = 1155, .type = 1219, .clearance = 0, .crew = 2, .guns = &.{ .{ .name = 1236, .count = 2 }, .{ .name = 1243, .count = 2 }, .{ .name = 1235, .count = 0 } }, .specials = &.{}, .shape = 20, .ship_type = 43 },
        .{ .name = 1195, .type = 1218, .clearance = 0, .crew = 2, .guns = &.{ .{ .name = 1236, .count = 2 }, .{ .name = 1243, .count = 2 }, .{ .name = 1235, .count = 0 } }, .specials = &.{}, .shape = 21, .ship_type = 41 },
        .{ .name = 1165, .type = 1219, .clearance = 0, .crew = 2, .guns = &.{ .{ .name = 1236, .count = 2 }, .{ .name = 1243, .count = 2 }, .{ .name = 1261, .count = 2 } }, .specials = &.{}, .shape = 28, .ship_type = 46 },
    },
};

/// A capital ship: the strings of its name, of when it was commissioned and of its type,
/// displacement, propulsion, spacecraft and armament, its crew, the string of its description, and
/// the shape of its picture in `capships.spr` (-1 for none).
pub const Ship = struct { name: u16, commissioned: u16, type: u16, displacement: u16, propulsion: u16, spacecraft: u16, armament: u16, crew: i16, description: u16, shape: i16 };

/// By side, the Alliance's first.
pub const ships = [2][]const Ship{
    &.{ // alliance
        .{ .name = 1262, .commissioned = 1263, .type = 1264, .displacement = 1265, .propulsion = 1266, .spacecraft = 1267, .armament = 1268, .crew = 4, .description = 1269, .shape = 1 },
        .{ .name = 1270, .commissioned = 1271, .type = 1272, .displacement = 1273, .propulsion = 1274, .spacecraft = 1275, .armament = 1276, .crew = 443, .description = 1277, .shape = 2 },
        .{ .name = 1278, .commissioned = 1279, .type = 1280, .displacement = 1281, .propulsion = 1282, .spacecraft = 1283, .armament = 1284, .crew = 409, .description = 1285, .shape = 4 },
        .{ .name = 1286, .commissioned = 1287, .type = 1288, .displacement = 1289, .propulsion = 1290, .spacecraft = 1291, .armament = 1292, .crew = 8, .description = 1293, .shape = 5 },
        .{ .name = 1313, .commissioned = 1314, .type = 1315, .displacement = 1316, .propulsion = 1317, .spacecraft = 1318, .armament = 1319, .crew = 4, .description = 1320, .shape = 7 },
        .{ .name = 1321, .commissioned = 1322, .type = 1323, .displacement = 1324, .propulsion = 1325, .spacecraft = 1326, .armament = 1327, .crew = 498, .description = 1328, .shape = 14 },
        .{ .name = 1329, .commissioned = 1330, .type = 1331, .displacement = 1332, .propulsion = 1333, .spacecraft = 1334, .armament = 1335, .crew = 131, .description = 1336, .shape = 8 },
        .{ .name = 1337, .commissioned = 1338, .type = 1339, .displacement = 1340, .propulsion = 1341, .spacecraft = 1342, .armament = 1343, .crew = 443, .description = 1344, .shape = 2 },
        .{ .name = 1345, .commissioned = 1346, .type = 1347, .displacement = 1348, .propulsion = 1349, .spacecraft = 1350, .armament = 1351, .crew = 12, .description = 1352, .shape = 11 },
        .{ .name = 1353, .commissioned = 1354, .type = 1355, .displacement = 1356, .propulsion = 1357, .spacecraft = 1358, .armament = 1359, .crew = 26, .description = 1360, .shape = 10 },
        .{ .name = 1361, .commissioned = 1362, .type = 1363, .displacement = 1364, .propulsion = 1365, .spacecraft = 1366, .armament = 1367, .crew = 54, .description = 1368, .shape = 13 },
        .{ .name = 1369, .commissioned = 1370, .type = 1371, .displacement = 1372, .propulsion = 1373, .spacecraft = 1374, .armament = 1375, .crew = 478, .description = 1376, .shape = 14 },
        .{ .name = 1377, .commissioned = 1378, .type = 1379, .displacement = 1380, .propulsion = 1381, .spacecraft = 1382, .armament = 1383, .crew = 8, .description = 1384, .shape = 16 },
        .{ .name = 1385, .commissioned = 1386, .type = 1387, .displacement = 1388, .propulsion = 1389, .spacecraft = 1390, .armament = 1391, .crew = 54, .description = 1392, .shape = 17 },
        .{ .name = 1393, .commissioned = 1394, .type = 1395, .displacement = 1396, .propulsion = 1397, .spacecraft = 1398, .armament = 1399, .crew = 292, .description = 1400, .shape = 19 },
        .{ .name = 1401, .commissioned = 1402, .type = 1403, .displacement = 1404, .propulsion = 1405, .spacecraft = 1406, .armament = 1407, .crew = 4, .description = 1408, .shape = 20 },
        .{ .name = 1409, .commissioned = 1410, .type = 1411, .displacement = 1412, .propulsion = 1413, .spacecraft = 1414, .armament = 1415, .crew = 4, .description = 1416, .shape = 22 },
        .{ .name = 1417, .commissioned = 1418, .type = 1419, .displacement = 1420, .propulsion = 1421, .spacecraft = 1422, .armament = 1423, .crew = 150, .description = 1424, .shape = 23 },
        .{ .name = 1425, .commissioned = 1426, .type = 1427, .displacement = 1428, .propulsion = 1429, .spacecraft = 1430, .armament = 1431, .crew = 498, .description = 1432, .shape = 25 },
        .{ .name = 1433, .commissioned = 1434, .type = 1435, .displacement = 1436, .propulsion = 1437, .spacecraft = 1438, .armament = 1439, .crew = 478, .description = 1440, .shape = 25 },
        .{ .name = 1441, .commissioned = 1442, .type = 1443, .displacement = 1444, .propulsion = 1445, .spacecraft = 1446, .armament = 1447, .crew = 587, .description = 1448, .shape = 26 },
    },
    &.{ // coalition
        .{ .name = 1449, .commissioned = 1450, .type = 1451, .displacement = 1452, .propulsion = 1453, .spacecraft = 1454, .armament = 1455, .crew = 6, .description = 1456, .shape = 28 },
        .{ .name = 1457, .commissioned = 1458, .type = 1459, .displacement = 1460, .propulsion = 1461, .spacecraft = 1462, .armament = 1463, .crew = 419, .description = 1464, .shape = 29 },
        .{ .name = 1465, .commissioned = 1466, .type = 1467, .displacement = 1468, .propulsion = 1469, .spacecraft = 1470, .armament = 1471, .crew = 147, .description = 1472, .shape = 31 },
        .{ .name = 1473, .commissioned = 1474, .type = 1475, .displacement = 1476, .propulsion = 1477, .spacecraft = 1478, .armament = 1479, .crew = 559, .description = 1480, .shape = 32 },
        .{ .name = 1489, .commissioned = 1490, .type = 1491, .displacement = 1492, .propulsion = 1493, .spacecraft = 1494, .armament = 1495, .crew = 29, .description = 1496, .shape = 35 },
        .{ .name = 1497, .commissioned = 1498, .type = 1499, .displacement = 1500, .propulsion = 1501, .spacecraft = 1502, .armament = 1503, .crew = 6, .description = 1504, .shape = 37 },
        .{ .name = 1505, .commissioned = 1506, .type = 1507, .displacement = 1508, .propulsion = 1509, .spacecraft = 1510, .armament = 1511, .crew = 3, .description = 1512, .shape = 38 },
        .{ .name = 1513, .commissioned = 1514, .type = 1515, .displacement = 1516, .propulsion = 1517, .spacecraft = 1518, .armament = 1519, .crew = 151, .description = 1520, .shape = 40 },
        .{ .name = 1906, .commissioned = 1907, .type = 1908, .displacement = 1909, .propulsion = 1910, .spacecraft = 1911, .armament = 1912, .crew = 477, .description = 1913, .shape = 46 },
        .{ .name = 1898, .commissioned = 1899, .type = 1900, .displacement = 1901, .propulsion = 1902, .spacecraft = 1903, .armament = 1904, .crew = 468, .description = 1905, .shape = 41 },
        .{ .name = 1521, .commissioned = 1522, .type = 1523, .displacement = 1524, .propulsion = 1525, .spacecraft = 1526, .armament = 1527, .crew = 463, .description = 1528, .shape = 41 },
        .{ .name = 1890, .commissioned = 1891, .type = 1892, .displacement = 1893, .propulsion = 1894, .spacecraft = 1895, .armament = 1896, .crew = 419, .description = 1897, .shape = 29 },
        .{ .name = 1529, .commissioned = 1530, .type = 1531, .displacement = 1532, .propulsion = 1533, .spacecraft = 1534, .armament = 1535, .crew = 162, .description = 1536, .shape = 56 },
        .{ .name = 1537, .commissioned = 1538, .type = 1539, .displacement = 1540, .propulsion = 1541, .spacecraft = 1542, .armament = 1543, .crew = 59, .description = 1544, .shape = 43 },
        .{ .name = 1545, .commissioned = 1546, .type = 1547, .displacement = 1548, .propulsion = 1549, .spacecraft = 1550, .armament = 1551, .crew = 151, .description = 1552, .shape = 40 },
        .{ .name = 1553, .commissioned = 1554, .type = 1555, .displacement = 1556, .propulsion = 1557, .spacecraft = 1558, .armament = 1559, .crew = 468, .description = 1560, .shape = 44 },
        .{ .name = 1561, .commissioned = 1562, .type = 1563, .displacement = 1564, .propulsion = 1565, .spacecraft = 1566, .armament = 1567, .crew = 477, .description = 1568, .shape = 46 },
        .{ .name = 1569, .commissioned = 1570, .type = 1571, .displacement = 1572, .propulsion = 1573, .spacecraft = 1574, .armament = 1575, .crew = 18, .description = 1576, .shape = 47 },
        .{ .name = 1577, .commissioned = 1578, .type = 1579, .displacement = 1580, .propulsion = 1581, .spacecraft = 1582, .armament = 1583, .crew = 22, .description = 1584, .shape = 49 },
        .{ .name = 1585, .commissioned = 1586, .type = 1587, .displacement = 1588, .propulsion = 1589, .spacecraft = 1590, .armament = 1591, .crew = 18, .description = 1592, .shape = 50 },
        .{ .name = 1593, .commissioned = 1594, .type = 1595, .displacement = 1596, .propulsion = 1597, .spacecraft = 1598, .armament = 1599, .crew = 2, .description = 1600, .shape = 52 },
        .{ .name = 1601, .commissioned = 1602, .type = 1603, .displacement = 1604, .propulsion = 1605, .spacecraft = 1606, .armament = 1607, .crew = 59, .description = 1608, .shape = 53 },
        .{ .name = 1609, .commissioned = 1610, .type = 1611, .displacement = 1612, .propulsion = 1613, .spacecraft = 1614, .armament = 1615, .crew = 162, .description = 1616, .shape = 56 },
        .{ .name = 1617, .commissioned = 1618, .type = 1619, .displacement = 1620, .propulsion = 1621, .spacecraft = 1622, .armament = 1623, .crew = 468, .description = 1624, .shape = 44 },
        .{ .name = 1625, .commissioned = 1626, .type = 1627, .displacement = 1628, .propulsion = 1629, .spacecraft = 1630, .armament = 1631, .crew = 6, .description = 1632, .shape = 55 },
        .{ .name = 1914, .commissioned = 1915, .type = 1916, .displacement = 1917, .propulsion = 1918, .spacecraft = 1919, .armament = 1920, .crew = 162, .description = 1921, .shape = 56 },
        .{ .name = 1633, .commissioned = 1634, .type = 1635, .displacement = 1636, .propulsion = 1637, .spacecraft = 1638, .armament = 1639, .crew = 162, .description = 1640, .shape = 56 },
    },
};

/// A squadron: the strings of its name, class, leader, base, nation and history, the shape of its
/// picture in `squads.spr`, and the block of the palette it is drawn with.
pub const Squadron = struct { name: u16, class: u16, leader: u16, base: u16, nation: u16, text: u16, shape: i16, palette: i16 };

/// By side, the Alliance's first.
pub const squadrons = [2][]const Squadron{
    &.{ // alliance
        .{ .name = 446, .class = 419, .leader = 421, .base = 501, .nation = 526, .text = 474, .shape = 21, .palette = 20 },
        .{ .name = 447, .class = 420, .leader = 422, .base = 502, .nation = 526, .text = 475, .shape = 22, .palette = 20 },
        .{ .name = 448, .class = 420, .leader = 423, .base = 503, .nation = 526, .text = 476, .shape = 6, .palette = 4 },
        .{ .name = 449, .class = 419, .leader = 424, .base = 504, .nation = 526, .text = 477, .shape = 25, .palette = 24 },
        .{ .name = 450, .class = 419, .leader = 425, .base = 505, .nation = 527, .text = 478, .shape = 2, .palette = 0 },
        .{ .name = 451, .class = 420, .leader = 426, .base = 506, .nation = 528, .text = 479, .shape = 17, .palette = 16 },
        .{ .name = 452, .class = 419, .leader = 427, .base = 507, .nation = 528, .text = 480, .shape = 18, .palette = 16 },
        .{ .name = 453, .class = 419, .leader = 428, .base = 506, .nation = 528, .text = 481, .shape = 5, .palette = 4 },
        .{ .name = 454, .class = 419, .leader = 429, .base = 508, .nation = 529, .text = 482, .shape = 7, .palette = 4 },
        .{ .name = 455, .class = 419, .leader = 430, .base = 509, .nation = 529, .text = 483, .shape = 19, .palette = 16 },
        .{ .name = 456, .class = 420, .leader = 431, .base = 510, .nation = 530, .text = 484, .shape = 9, .palette = 8 },
        .{ .name = 457, .class = 420, .leader = 431, .base = 510, .nation = 530, .text = 485, .shape = 10, .palette = 8 },
        .{ .name = 458, .class = 419, .leader = 432, .base = 512, .nation = 531, .text = 486, .shape = 1, .palette = 0 },
        .{ .name = 459, .class = 420, .leader = 433, .base = 513, .nation = 530, .text = 487, .shape = 3, .palette = 0 },
        .{ .name = 460, .class = 419, .leader = 434, .base = 514, .nation = 531, .text = 488, .shape = 13, .palette = 12 },
        .{ .name = 461, .class = 419, .leader = 435, .base = 511, .nation = 532, .text = 489, .shape = 23, .palette = 20 },
        .{ .name = 462, .class = 419, .leader = 436, .base = 515, .nation = 532, .text = 490, .shape = 14, .palette = 12 },
        .{ .name = 463, .class = 420, .leader = 437, .base = 516, .nation = 532, .text = 491, .shape = 15, .palette = 12 },
        .{ .name = 464, .class = 420, .leader = 438, .base = 516, .nation = 532, .text = 492, .shape = 11, .palette = 8 },
    },
    &.{ // coalition
        .{ .name = 465, .class = 419, .leader = 439, .base = 517, .nation = 533, .text = 493, .shape = 32, .palette = 30 },
        .{ .name = 466, .class = 419, .leader = 440, .base = 518, .nation = 534, .text = 494, .shape = 27, .palette = 26 },
        .{ .name = 467, .class = 419, .leader = 441, .base = 519, .nation = 535, .text = 495, .shape = 28, .palette = 26 },
        .{ .name = 468, .class = 419, .leader = 442, .base = 520, .nation = 534, .text = 496, .shape = 29, .palette = 26 },
        .{ .name = 469, .class = 420, .leader = 443, .base = 521, .nation = 534, .text = 497, .shape = 31, .palette = 30 },
        .{ .name = 470, .class = 419, .leader = 444, .base = 522, .nation = 533, .text = 498, .shape = 35, .palette = 34 },
        .{ .name = 471, .class = 420, .leader = 445, .base = 523, .nation = 533, .text = 499, .shape = 36, .palette = 34 },
        .{ .name = 472, .class = 420, .leader = 473, .base = 524, .nation = 533, .text = 500, .shape = 33, .palette = 30 },
    },
};

/// A person: the strings of their name, nationality, age, ship and call sign (0 for none), and of
/// their military history, training and background, and the shape of their portrait in
/// `persons.spr`.
pub const Person = struct { name: u16, nationality: u16, age: u16, ship: u16, call_sign: u16, history: u16, training: u16, background: u16, shape: i16 };

/// By side, the Alliance's first.
pub const personnel = [2][]const Person{
    &.{ // alliance
        .{ .name = 756, .nationality = 813, .age = 792, .ship = 868, .call_sign = 837, .history = 886, .training = 923, .background = 959, .shape = 1 },
        .{ .name = 757, .nationality = 821, .age = 793, .ship = 869, .call_sign = 838, .history = 887, .training = 924, .background = 960, .shape = 2 },
        .{ .name = 758, .nationality = 814, .age = 794, .ship = 981, .call_sign = 839, .history = 888, .training = 925, .background = 961, .shape = 3 },
        .{ .name = 759, .nationality = 813, .age = 795, .ship = 859, .call_sign = 840, .history = 889, .training = 926, .background = 962, .shape = 4 },
        .{ .name = 760, .nationality = 813, .age = 796, .ship = 868, .call_sign = 841, .history = 890, .training = 927, .background = 963, .shape = 5 },
        .{ .name = 761, .nationality = 822, .age = 797, .ship = 869, .call_sign = 842, .history = 891, .training = 928, .background = 964, .shape = 6 },
        .{ .name = 762, .nationality = 813, .age = 798, .ship = 869, .call_sign = 843, .history = 892, .training = 929, .background = 965, .shape = 7 },
        .{ .name = 741, .nationality = 813, .age = 777, .ship = 0, .call_sign = 826, .history = 870, .training = 908, .background = 944, .shape = 25 },
        .{ .name = 742, .nationality = 814, .age = 778, .ship = 858, .call_sign = 0, .history = 873, .training = 909, .background = 945, .shape = 26 },
        .{ .name = 763, .nationality = 823, .age = 799, .ship = 859, .call_sign = 844, .history = 893, .training = 943, .background = 966, .shape = 8 },
        .{ .name = 764, .nationality = 813, .age = 800, .ship = 982, .call_sign = 845, .history = 894, .training = 930, .background = 967, .shape = 10 },
        .{ .name = 765, .nationality = 813, .age = 801, .ship = 863, .call_sign = 846, .history = 895, .training = 931, .background = 968, .shape = 11 },
        .{ .name = 743, .nationality = 813, .age = 779, .ship = 0, .call_sign = 827, .history = 874, .training = 910, .background = 946, .shape = 27 },
        .{ .name = 766, .nationality = 983, .age = 802, .ship = 863, .call_sign = 847, .history = 896, .training = 932, .background = 969, .shape = 12 },
        .{ .name = 767, .nationality = 815, .age = 803, .ship = 981, .call_sign = 848, .history = 897, .training = 933, .background = 970, .shape = 13 },
        .{ .name = 768, .nationality = 984, .age = 804, .ship = 871, .call_sign = 849, .history = 898, .training = 934, .background = 971, .shape = 14 },
        .{ .name = 744, .nationality = 813, .age = 780, .ship = 859, .call_sign = 828, .history = 875, .training = 911, .background = 947, .shape = 28 },
        .{ .name = 769, .nationality = 825, .age = 805, .ship = 872, .call_sign = 850, .history = 899, .training = 935, .background = 972, .shape = 15 },
        .{ .name = 770, .nationality = 813, .age = 806, .ship = 862, .call_sign = 851, .history = 900, .training = 936, .background = 973, .shape = 16 },
        .{ .name = 771, .nationality = 814, .age = 807, .ship = 861, .call_sign = 852, .history = 901, .training = 937, .background = 974, .shape = 17 },
        .{ .name = 772, .nationality = 813, .age = 808, .ship = 872, .call_sign = 853, .history = 902, .training = 938, .background = 975, .shape = 19 },
        .{ .name = 745, .nationality = 815, .age = 781, .ship = 860, .call_sign = 0, .history = 876, .training = 912, .background = 948, .shape = 29 },
        .{ .name = 773, .nationality = 823, .age = 809, .ship = 862, .call_sign = 854, .history = 903, .training = 939, .background = 976, .shape = 20 },
        .{ .name = 774, .nationality = 813, .age = 810, .ship = 982, .call_sign = 855, .history = 904, .training = 940, .background = 977, .shape = 21 },
        .{ .name = 746, .nationality = 816, .age = 782, .ship = 0, .call_sign = 0, .history = 877, .training = 913, .background = 949, .shape = 30 },
        .{ .name = 747, .nationality = 816, .age = 783, .ship = 861, .call_sign = 829, .history = 878, .training = 914, .background = 950, .shape = 31 },
        .{ .name = 775, .nationality = 813, .age = 811, .ship = 861, .call_sign = 856, .history = 905, .training = 941, .background = 978, .shape = 22 },
        .{ .name = 748, .nationality = 815, .age = 784, .ship = 981, .call_sign = 830, .history = 879, .training = 915, .background = 951, .shape = 32 },
        .{ .name = 749, .nationality = 813, .age = 785, .ship = 863, .call_sign = 831, .history = 880, .training = 916, .background = 952, .shape = 34 },
        .{ .name = 776, .nationality = 813, .age = 812, .ship = 863, .call_sign = 857, .history = 906, .training = 942, .background = 979, .shape = 23 },
    },
    &.{ // coalition
        .{ .name = 753, .nationality = 819, .age = 789, .ship = 865, .call_sign = 834, .history = 907, .training = 920, .background = 956, .shape = 39 },
        .{ .name = 750, .nationality = 817, .age = 786, .ship = 0, .call_sign = 0, .history = 881, .training = 917, .background = 953, .shape = 36 },
        .{ .name = 751, .nationality = 985, .age = 787, .ship = 864, .call_sign = 832, .history = 882, .training = 918, .background = 954, .shape = 37 },
        .{ .name = 752, .nationality = 985, .age = 788, .ship = 864, .call_sign = 833, .history = 883, .training = 919, .background = 955, .shape = 38 },
        .{ .name = 754, .nationality = 986, .age = 790, .ship = 866, .call_sign = 835, .history = 884, .training = 921, .background = 957, .shape = 40 },
        .{ .name = 755, .nationality = 819, .age = 791, .ship = 867, .call_sign = 836, .history = 885, .training = 922, .background = 958, .shape = 41 },
    },
};

/// A pilot of the KILLBOARD: the strings of their name, the line below it and their ship, the kills
/// they start with, the mean and the spread of the kills each mission adds, and the shape of their
/// portrait in `kills.spr`.
pub const Pilot = struct { name: u16, call_sign: u16, ship: u16, base_kills: i16, mean: f32, spread: f32, shape: i16 };

pub const pilots = [_]Pilot{
    .{ .name = 1301, .call_sign = 1305, .ship = 1309, .base_kills = 29, .mean = 11, .spread = 3, .shape = 3 },
    .{ .name = 1303, .call_sign = 1307, .ship = 1311, .base_kills = 34, .mean = 8, .spread = 4, .shape = 21 },
    .{ .name = 1304, .call_sign = 1308, .ship = 1312, .base_kills = 42, .mean = 11, .spread = 3, .shape = 17 },
    .{ .name = 1719, .call_sign = 1720, .ship = 1721, .base_kills = 26, .mean = 5, .spread = 4, .shape = 9 },
    .{ .name = 1722, .call_sign = 1723, .ship = 1724, .base_kills = 28, .mean = 6, .spread = 3, .shape = 19 },
    .{ .name = 1725, .call_sign = 1726, .ship = 1727, .base_kills = 32, .mean = 7, .spread = 3, .shape = 14 },
    .{ .name = 1728, .call_sign = 1729, .ship = 1730, .base_kills = 43, .mean = 8, .spread = 3, .shape = 8 },
    .{ .name = 1731, .call_sign = 1732, .ship = 1733, .base_kills = 46, .mean = 9, .spread = 2, .shape = 20 },
    .{ .name = 1737, .call_sign = 1738, .ship = 1739, .base_kills = 18, .mean = 9, .spread = 3, .shape = 18 },
    .{ .name = 1740, .call_sign = 1741, .ship = 1742, .base_kills = 32, .mean = 12, .spread = 3, .shape = 11 },
    .{ .name = 1743, .call_sign = 1744, .ship = 1745, .base_kills = 22, .mean = 7, .spread = 3, .shape = 12 },
    .{ .name = 1746, .call_sign = 1747, .ship = 1748, .base_kills = 21, .mean = 8, .spread = 3, .shape = 7 },
    .{ .name = 1749, .call_sign = 1750, .ship = 1751, .base_kills = 39, .mean = 11, .spread = 2, .shape = 15 },
    .{ .name = 1752, .call_sign = 1753, .ship = 1754, .base_kills = 46, .mean = 10, .spread = 4, .shape = 22 },
    .{ .name = 1755, .call_sign = 1756, .ship = 1757, .base_kills = 61, .mean = 12, .spread = 3, .shape = 16 },
    .{ .name = 1758, .call_sign = 1759, .ship = 1760, .base_kills = 38, .mean = 9, .spread = 3, .shape = 13 },
    .{ .name = 1761, .call_sign = 1762, .ship = 1763, .base_kills = 35, .mean = 10, .spread = 2, .shape = 5 },
    .{ .name = 1764, .call_sign = 1765, .ship = 1766, .base_kills = 50, .mean = 11, .spread = 3, .shape = 10 },
    .{ .name = 1767, .call_sign = 1768, .ship = 1769, .base_kills = 33, .mean = 11, .spread = 3, .shape = 4 },
};
