//! Reads the locker's tables out of the payload, which its drawing reads (`medal_display_draw`,
//! `0x00436B20`): where each of the six medals and the six ribbons stands, on the Reliant and on
//! the Yamato, and the shape of its set it shows on each frame of the lid's movie, 0 for none.
//!
//! A table of shapes holds a row of bytes for each award, as long as the drawing steps through it
//! (`Layout.row`); a table of places, the six awards' x, words, then their y.

const std = @import("std");
const Io = std.Io;

const image = @import("image.zig");
const testing = @import("testing.zig");

/// The medals, and the ribbons, a carrier's tables hold.
pub const awards = 6;

/// The tables, by the names the emitted file gives them.
pub const Table = enum { reliant_medals, reliant_ribbons, yamato_medals, yamato_ribbons };

/// Where a table's shapes lie, and how long each award's row is; and where its places lie.
pub const Layout = struct {
    shapes: u32,
    row: u32,
    xs: u32,
    ys: u32,
};

pub const layouts = std.EnumArray(Table, Layout).init(.{
    .reliant_medals = .{ .shapes = 0x004E77C0, .row = 0x40, .xs = 0x004E79D0, .ys = 0x004E79E8 },
    .reliant_ribbons = .{ .shapes = 0x004E7A60, .row = 0x17, .xs = 0x004E7B1C, .ys = 0x004E7B34 },
    .yamato_medals = .{ .shapes = 0x004E7940, .row = 0x10, .xs = 0x004E79A0, .ys = 0x004E79B8 },
    .yamato_ribbons = .{ .shapes = 0x004E7A00, .row = 0x10, .xs = 0x004E7AEC, .ys = 0x004E7B04 },
});

/// How the locker shows an award: where it stands, and its shape on each frame of the lid's movie.
pub const Display = struct {
    at: [2]i32,
    shapes: []const u8,
};

pub const Tables = std.EnumArray(Table, [awards]Display);

pub fn read(arena: std.mem.Allocator, reader: image.Reader) (image.Error || std.mem.Allocator.Error)!Tables {
    var tables: Tables = undefined;
    for (std.enums.values(Table)) |table| {
        const layout = layouts.get(table);
        for (tables.getPtr(table), 0..) |*award, n| {
            const at: u32 = @intCast(n);
            award.* = .{
                .at = .{ try reader.int(i32, layout.xs + 4 * at), try reader.int(i32, layout.ys + 4 * at) },
                .shapes = try arena.dupe(u8, try reader.slice(layout.shapes + layout.row * at, layout.row)),
            };
        }
    }
    return tables;
}

/// What each table holds, for its doc comment.
const descriptions = std.EnumArray(Table, []const u8).init(.{
    .reliant_medals = "The Reliant's medals",
    .reliant_ribbons = "The Reliant's ribbons",
    .yamato_medals = "The Yamato's medals",
    .yamato_ribbons = "The Yamato's ribbons",
});

/// Writes `interface/locker/tables.zig`.
pub fn emit(w: *Io.Writer, tables: Tables) Io.Writer.Error!void {
    try w.writeAll(
        \\//! The locker's tables: where each of the six medals and the six ribbons stands on each
        \\//! carrier, and the shape of its set it shows on each frame of the lid's movie, 0 for none.
        \\//!
        \\//! Generated by `src/tools/tablegen` from the payload executable. Do not edit by hand; run
        \\//! `make locker-tables`.
        \\
        \\/// How the locker shows an award: where it stands, and its shape on each frame of the lid's
        \\/// movie.
        \\pub const Display = struct { at: [2]i32, shapes: []const u8 };
        \\
    );
    for (std.enums.values(Table)) |table| {
        const layout = layouts.get(table);
        try w.print(
            \\
            \\/// {s}: their shapes from 0x{X:0>8}, {d} frames each, and their
            \\/// places from 0x{X:0>8} and 0x{X:0>8}.
            \\pub const {s} = [{d}]Display{{
            \\
        , .{ descriptions.get(table), layout.shapes, layout.row, layout.xs, layout.ys, @tagName(table), awards });
        for (tables.get(table)) |award| {
            try w.print("    .{{ .at = .{{ {d}, {d} }}, .shapes = &.{{", .{ award.at[0], award.at[1] });
            for (award.shapes, 0..) |shape, n| try w.print("{s}{d}", .{ if (n == 0) " " else ", ", shape });
            try w.writeAll(" } },\n");
        }
        try w.writeAll("};\n");
    }
}

test read {
    const allocator = std.testing.allocator;
    var arena_state: std.heap.ArenaAllocator = .init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    // The tables' stretch of the payload, empty but for the Yamato's second medal: shapes 1 and 2
    // from its third frame, at (272, 153).
    const first = layouts.get(.reliant_medals).shapes;
    const bytes = try allocator.alloc(u8, 0x400);
    defer allocator.free(bytes);
    @memset(bytes, 0);
    const region: testing.Region = .{ .va = first, .bytes = bytes };
    const yamato = layouts.get(.yamato_medals);
    region.put(yamato.shapes + yamato.row + 2, &.{ 1, 2 });
    region.putWord(yamato.xs + 4, 272);
    region.putWord(yamato.ys + 4, 153);

    const payload = try testing.reader(allocator, &.{region});
    defer testing.freeReader(allocator, payload);
    const tables = try read(arena, payload);
    const medal = tables.get(.yamato_medals)[1];
    try std.testing.expectEqual([2]i32{ 272, 153 }, medal.at);
    try std.testing.expectEqualSlices(u8, &.{ 0, 0, 1, 2, 0 }, medal.shapes[0..5]);
    try std.testing.expectEqual(16, medal.shapes.len);
    try std.testing.expectEqual(64, tables.get(.reliant_medals)[0].shapes.len);
    try std.testing.expectEqual(23, tables.get(.reliant_ribbons)[5].shapes.len);

    var out: Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    try emit(&out.writer, tables);
    try testing.expectZig(out.written());
}
