//! Reads the pool of pilots that replace the wingmen who die out of the payload (`pilot_pool`): for
//! each record, the pilot by the pilot stats' number and its status as the game starts
//! (`pilots.Replacement`).

const std = @import("std");
const Io = std.Io;

const openreliant = @import("openreliant");
const pilots = openreliant.engine.game.pilots;
const Replacement = pilots.Replacement;

const image = @import("image.zig");
const testing = @import("testing.zig");
const zig_text = @import("zig_text.zig");

/// `pilot_pool`, which `update_pilots` (`0x0049CD70`) and `explode_ship_init` (`0x004086F0`) read.
pub const table: u32 = 0x005047D0;

/// The pool's records as the payload holds them, in `arena`.
pub fn read(arena: std.mem.Allocator, reader: image.Reader) (image.Error || std.mem.Allocator.Error)![]const Replacement {
    const records = try reader.records(Replacement, table, pilots.pool_size);
    const pool = try arena.alloc(Replacement, records.len);
    for (pool, records) |*held, record| held.* = .{ .pilot = record.pilot, .status = record.status };
    return pool;
}

/// Writes `pilots/pool.zig`.
pub fn emit(w: *Io.Writer, pool: []const Replacement) Io.Writer.Error!void {
    try w.print(
        \\//! The pool of pilots that replace the wingmen who die, as the game starts: each pilot by the
        \\//! pilot stats' number, and whether it's free.
        \\//!
        \\//! Generated by `src/tools/tablegen` from the payload executable's `pilot_pool` at
        \\//! 0x{X:0>8}, {d} pilots. Do not edit by hand; run `make pilot-pool-table`.
        \\
        \\const pilots = @import("../pilots.zig");
        \\
        \\/// The pool, in the order `update_pilots` takes from it.
        \\pub const pool = [{d}]pilots.Replacement{{
        \\
    , .{ table, pool.len, pool.len });
    for (pool) |held| {
        try w.print("    .{{ .pilot = {d}, .status = ", .{held.pilot});
        try zig_text.enumValue(w, held.status);
        try w.writeAll(" },\n");
    }
    try w.writeAll(
        \\};
        \\
    );
}

test read {
    const allocator = std.testing.allocator;
    var arena_state: std.heap.ArenaAllocator = .init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var bytes: [pilots.pool_size * @sizeOf(Replacement)]u8 = @splat(0);
    // The first pilot is 119 and free, the second 87 and dead.
    bytes[0..4].* = .{ 119, 0, 2, 0 };
    bytes[4..8].* = .{ 87, 0, 0, 0 };
    const region: testing.Region = .{ .va = table, .bytes = &bytes };
    const payload = try testing.reader(allocator, &.{region});
    defer testing.freeReader(allocator, payload);
    const pool = try read(arena, payload);
    try std.testing.expectEqual(pilots.pool_size, pool.len);
    try std.testing.expectEqual(Replacement{ .pilot = 119, .status = .free }, pool[0]);
    try std.testing.expectEqual(Replacement.Status.dead, pool[1].status);

    var out: Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    try emit(&out.writer, pool);
    try std.testing.expect(std.mem.indexOf(u8, out.written(), ".{ .pilot = 119, .status = .free },") != null);
    try testing.expectZig(out.written());
}
