//! Reads the rooms' views out of the payload (`rooms.View`): the Reliant's and the Yamato's, walked
//! from the views the code enters the rooms by (`rooms.Entry`) through each view's exits, and kept
//! in the order they lie in the executable, each exit then the place of the view it leads to.
//!
//! The views of the locker and the simulator's hotspots count exits they don't have, null
//! pointers the game never follows, as it leaves those views at once for their screens; the table
//! keeps only the exits there are.

const std = @import("std");
const Io = std.Io;

const openreliant = @import("openreliant");
const rooms = openreliant.engine.game.interface.rooms;
const View = rooms.View;

const image = @import("image.zig");
const testing = @import("testing.zig");
const zig_text = @import("zig_text.zig");

pub const Error = image.Error || error{TooManyViews};

/// The views, walked from `entries`.
pub fn read(arena: std.mem.Allocator, reader: image.Reader, entries: []const u32) (Error || std.mem.Allocator.Error)![]const View {
    var records: std.array_hash_map.Auto(u32, View.Record) = .empty;
    var pending: std.ArrayList(u32) = .empty;
    try pending.appendSlice(arena, entries);
    while (pending.pop()) |address| {
        if (address == 0 or records.contains(address)) continue;
        const record = try reader.record(View.Record, address);
        try records.put(arena, address, record);
        for (exitsOf(&record)) |exit| try pending.append(arena, @backingInt(exit));
    }
    const addresses = try arena.dupe(u32, records.keys());
    std.mem.sort(u32, addresses, {}, std.sort.asc(u32));
    if (addresses.len > std.math.maxInt(u8) + 1) return error.TooManyViews;

    const views = try arena.alloc(View, addresses.len);
    for (views, addresses) |*view, address| {
        const record = records.getPtr(address).?;
        var exits: std.ArrayList(u8) = .empty;
        for (exitsOf(record)) |exit| {
            if (exit == .null) continue;
            try exits.append(arena, @intCast(std.mem.findScalar(u32, addresses, @backingInt(exit)).?));
        }
        view.* = .{
            .address = address,
            .hotspot = record.hotspot,
            .movie = try optionalString(reader, record.movie),
            .loop = try optionalString(reader, record.loop),
            .label = @bitCast(record.label),
            .exits = exits.items,
            .action = record.action,
            .sound = if (record.sound < 0) null else @intCast(record.sound),
        };
    }
    return views;
}

/// The exits `record` counts, as far as a view has room for.
fn exitsOf(record: *const View.Record) []const openreliant.engine.Pointer(View.Record) {
    const count: usize = @intCast(std.math.clamp(record.exit_count, 0, View.max_exits));
    return record.exits[0..count];
}

fn optionalString(reader: image.Reader, address: openreliant.engine.Pointer(u8)) image.Error!?[]const u8 {
    return if (address == .null) null else try reader.string(@backingInt(address));
}

/// Writes `interface/rooms/views.zig`.
pub fn emit(w: *Io.Writer, views: []const View) Io.Writer.Error!void {
    try w.print(
        \\//! The rooms' views, the Reliant's and the Yamato's, in the order they lie in the executable:
        \\//! each with its hotspot, its movies, its label, its exits by their place in this table, its
        \\//! action and its sound.
        \\//!
        \\//! Generated by `src/tools/tablegen` from the payload executable, walked from the views the code
        \\//! enters the rooms by, {d} views. Do not edit by hand; run `make room-tables`.
        \\
        \\const rooms = @import("../rooms.zig");
        \\
        \\pub const views = [{d}]rooms.View{{
        \\
    , .{ views.len, views.len });
    for (views, 0..) |view, index| {
        const r = view.hotspot;
        try w.print("    // {d}\n    .{{ .address = 0x{X:0>8}, .hotspot = .{{ .x = {d}, .y = {d}, .width = {d}, .height = {d} }}, .movie = ", .{ index, view.address, r.x, r.y, r.width, r.height });
        try optionalText(w, view.movie);
        try w.writeAll(", .loop = ");
        try optionalText(w, view.loop);
        try w.print(", .label = 0x{X}, .exits = &.{{", .{view.label});
        for (view.exits, 0..) |exit, place| try w.print("{s}{d}", .{ if (place == 0) " " else ", ", exit });
        try w.writeAll(if (view.exits.len == 0) "}, .action = " else " }, .action = ");
        try zig_text.enumValue(w, view.action);
        if (view.sound) |sound| try w.print(", .sound = {d}", .{sound}) else try w.writeAll(", .sound = null");
        try w.writeAll(" },\n");
    }
    try w.writeAll(
        \\};
        \\
    );
}

fn optionalText(w: *Io.Writer, text: ?[]const u8) Io.Writer.Error!void {
    if (text) |shown| try w.print("\"{f}\"", .{std.zig.fmtString(shown)}) else try w.writeAll("null");
}

test read {
    const allocator = std.testing.allocator;
    var arena_state: std.heap.ArenaAllocator = .init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var bytes: [0x200]u8 = @splat(0);
    const at: u32 = 0x506000;
    const region: testing.Region = .{ .va = at, .bytes = &bytes };
    // Three views: the entry leads to the second and back to itself through it; the third, which
    // lies first, counts two exits it doesn't have.
    const entry = at + 0x60;
    const second = at + 0x90;
    const locker = at;
    region.putString(at + 0x100, "a2b.bik");
    region.putString(at + 0x110, "b_loop.bik");
    region.putRecord(entry, View.Record{
        .hotspot = .{ .x = 0, .y = 0, .width = 40, .height = 479 },
        .movie = @fromBackingInt(at + 0x100),
        .loop = .null,
        .label = 0xC3,
        .exit_count = 2,
        .exits = .{ @fromBackingInt(second), @fromBackingInt(locker), .null, .null },
        ._unknown_24 = 0,
        .action = .none,
        .sound = -1,
        ._unknown_2c = 0,
    });
    region.putRecord(second, View.Record{
        .hotspot = .{ .x = 562, .y = 0, .width = 78, .height = 480 },
        .movie = @fromBackingInt(at + 0x100),
        .loop = @fromBackingInt(at + 0x110),
        .label = 0x298,
        .exit_count = 1,
        .exits = .{ @fromBackingInt(entry), .null, .null, .null },
        ._unknown_24 = 0,
        .action = .news,
        .sound = 3,
        ._unknown_2c = 0,
    });
    region.putRecord(locker, View.Record{
        .hotspot = .{ .x = 181, .y = 150, .width = 340, .height = 150 },
        .movie = .null,
        .loop = .null,
        .label = 0xD1,
        .exit_count = 2,
        .exits = @splat(.null),
        ._unknown_24 = 0,
        .action = .locker,
        .sound = -1,
        ._unknown_2c = 0,
    });

    const payload = try testing.reader(allocator, &.{region});
    defer testing.freeReader(allocator, payload);
    const views = try read(arena, payload, &.{entry});
    try std.testing.expectEqual(3, views.len);
    // In the order they lie.
    try std.testing.expectEqual(locker, views[0].address);
    try std.testing.expectEqual(0, views[0].exits.len);
    try std.testing.expectEqual(null, views[0].movie);
    try std.testing.expectEqualSlices(u8, &.{ 2, 0 }, views[1].exits);
    try std.testing.expectEqualStrings("a2b.bik", views[1].movie.?);
    try std.testing.expectEqual(null, views[1].loop);
    try std.testing.expectEqual(null, views[1].sound);
    try std.testing.expectEqualStrings("b_loop.bik", views[2].loop.?);
    try std.testing.expectEqual(.news, views[2].action);
    try std.testing.expectEqual(3, views[2].sound.?);
    try std.testing.expectEqual(0x298, views[2].label);

    var out: Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    try emit(&out.writer, views);
    try testing.expectZig(out.written());
}
